### ISSUE TITLE
Error after downloading dataset

### ISSUE THREAD

**Issue by gvrancken** [georgw777/chesscog#13]
After running `python -m chesscog.data_synthesis.download_dataset`, I get the following error:

```
[2021-08-29 08:51:22,147] {download_dataset.py:42} INFO - Merging train dataset
sh: 1: zip: not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/data/render/train_full.zip' -> '/data/render/train.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/chess/chesscog/data_synthesis/download_dataset.py", line 50, in <module>
    shutil.move(folder / "train_full.zip", folder / "train.zip")
  File "/usr/local/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/usr/local/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/data/render/train_full.zip'
```

**Comment by georg-wolflein** [comment]
You're using the Dockerfile right? It seems that I forgot to install the `zip` package in the updated Dockerfile. A quick solution is to run
```
apt update && apt install -y zip
```
in the docker container, then delete `/data/render`, and finally re-run `python -m chesscog.data_synthesis.download_dataset`.

I will fix this in the Dockerfiles shortly.
