### ISSUE TITLE
Error when uses transfer_learning.train

### ISSUE THREAD

**Issue by daimianw** [georgw777/chesscog#15]
Thanks for the interesting project! I am trying to apply the project on a smaller chess board. When performing model fine tuning, I encountered the following error, for which I have not found a way around. Could you please help? The error message is below:

"
jetson@yahboom:~/chesscog$ python3.9 -m chesscog.transfer_learning.train
[2023-04-19 14:29:52,990] {train.py:43} INFO - Starting training for occupancy_classifier
[2023-04-19 14:29:53,164] {train.py:55} INFO - Starting training in /home/jetson/chesscog/runs/transfer_learning/occupancy_classifier
[2023-04-19 14:29:53,165] {train.py:61} WARNING - The folder /home/jetson/chesscog/runs/transfer_learning/occupancy_classifier already exists and will be overwritten by this run
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jetson/chesscog/chesscog/transfer_learning/train.py", line 44, in <module>
    _train_model(model_type)
  File "/home/jetson/chesscog/chesscog/transfer_learning/train.py", line 35, in _train_model
    train_model(cfg, run_dir, model, is_inception,
  File "/home/jetson/chesscog/chesscog/core/training/train.py", line 80, in train_model
    dataset = build_dataset(cfg, Datasets.TRAIN)
  File "/home/jetson/chesscog/chesscog/core/dataset/dataset.py", line 70, in build_dataset
    dataset = torchvision.datasets.ImageFolder(root=URI(cfg.DATASET.PATH) / mode.value,
  File "/home/jetson/.local/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 310, in __init__
    super(ImageFolder, self).__init__(root, loader, IMG_EXTENSIONS if is_valid_file is None else None,
  File "/home/jetson/.local/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 145, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/jetson/.local/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 221, in find_classes
    return find_classes(directory)
  File "/home/jetson/.local/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 42, in find_classes
    raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
FileNotFoundError: Couldn't find any class folder in /home/jetson/chess_data/transfer_learning/occupancy/train.
"

**Comment by georg-wolflein** [comment]
Could you try running `python -m chesscog.transfer_learning.create_dataset` and then run the training again? Also, check out the instructions in section C.2.6 [here](https://github.com/georg-wolflein/chesscog-report/raw/master/report.pdf).

**Comment by daimianw** [comment]
Yes. It unblocked the training. Thanks for the quick response!
