### ISSUE TITLE
Can't get download scripts to work

### ISSUE THREAD

**Issue by leason** [georgw777/chesscog#17]
I'm very interested in testing your project.  I had some difficulty getting the environment set up, but can now execute the download scripts.  I get this error:
`(.venv) chesscog leason$ python -m chesscog.data_synthesis.download_dataset
[2023-10-30 11:36:30,850] {download_dataset.py:44} INFO - Downloading rendered dataset from OSF
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.29G/4.29G [05:58<00:00, 12.0Mbytes/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 522M/522M [00:46<00:00, 11.3Mbytes/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 223M/223M [00:19<00:00, 11.7Mbytes/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.42G/2.42G [03:38<00:00, 11.0Mbytes/s]
4files [10:53, 163.30s/files]█████████████████████████████████████████████████████████████████████████████████████████████████████▊| 2.41G/2.42G [03:38<00:00, 9.04Mbytes/s]
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/leason/src/chesscog/chesscog/data_synthesis/download_dataset.py", line 49, in <module>
    os.makedirs(folder.parent, exist_ok=True)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py", line 103, in split
    p = os.fspath(p)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 632, in __fspath__
    return str(self)
  File "/Users/leason/src/chesscog/.venv/lib/python3.10/site-packages/recap/path_manager.py", line 145, in __str__
    return str(self._local_path)
AttributeError: 'URI' object has no attribute '_local_path'`

I've confirmed that the files are downloaded to the tmp directory, but I'm not sure where the download_dataset.py script is actually trying to put them.  The value of the `folder` variable is "data://render" so I'm not sure what is supposed to happen when the OS tries to makedirs for folder.parent on line 49.

**Comment by georg-wolflein** [comment]
Hi, I think this error comes up because one of the dependencies, `recap` was not compatible with Python 3.10. I just fixed this issue in recap v0.1.7 (https://pypi.org/project/recap/). Please reinstall/update the recap package and try again.

**Comment by leason** [comment]
Ah, that's great.  I'd tried older versions of recap thinking that might be
the cause.  Thank you for the update - that seems to have fixed the issue.

My goal is to build a raspberry pi based chess buddy that will have some
personality and make it possible to play more interesting games against AI
(and eventually friends far away) on any (reasonable) physical board, so
your project is very interesting to me.  Thank you for sharing the code!
Let me know if you'd like me to share whatever I end up building with this.

Lee

**Comment by georg-wolflein** [comment]
That sounds interesting! Yes please, do share the project when you are finished:)
Here is a paper that came out recently which may be interesting to you as well: https://arxiv.org/abs/2310.04086.

Georg
